--LAB2
    --#1
        CREATE TABLESPACE TS_SVA
            DATAFILE 'TS_SVA.dbf'
            SIZE 7M
            AUTOEXTEND ON NEXT 5M
            MAXSIZE 20M
            EXTENT MANAGEMENT LOCAL
    --#2    
        CREATE TEMPORARY TABLESPACE TS_SVA_TEMP
            TEMPFILE 'TS_SVA_TEMP.dbf'
            SIZE 5M
            AUTOEXTEND ON NEXT 3M
            MAXSIZE 30M
            EXTENT MANAGEMENT LOCAL
    --#3
        SELECT TABLESPACE_NAME,STATUS, CONTENTS LOGGIN FROM SYS.DBA_TABLESPACES;
        DROP TABLESPACE TS_SVA_TEMP;
        DROP TABLESPACE TS_SVA;
    --#4
        CREATE ROLE RL_SVACORE;
        GRANT CREATE SESSION,
              CREATE ANY TABLE,
              CREATE ANY VIEW,
              CREATE PROCEDURE TO RL_SVACORE;
        GRANT DROP ANY TABLE TO RL_SVACORE;
        GRANT DROP ANY VIEW TO RL_SVACORE;
        GRANT DROP ANY PROCEDURE TO RL_SVACORE;
        
        DROP ROLE RL_SVACORE
    --#5
        SELECT * FROM DBA_ROLES WHERE ROLE LIKE 'RL_SVACORE';    
        SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE ='RL_SVACORE';
    --#6
        CREATE PROFILE PF_SVACORE LIMIT
            PASSWORD_LIFE_TIME 180
            SESSIONS_PER_USER 3
            FAILED_LOGIN_ATTEMPTS 7
            PASSWORD_LOCK_TIME 1
            PASSWORD_REUSE_TIME 10
            PASSWORD_GRACE_TIME DEFAULT
            CONNECT_TIME 180
            IDLE_TIME 30
    --#7
        SELECT *FROM DBA_PROFILES ;
        SELECT *FROM DBA_PROFILES WHERE PROFILE = 'PF_SVACORE';
        SELECT *FROM DBA_PROFILES WHERE PROFILE = 'DEFAULT';
    --#8
        CREATE USER SVACORE IDENTIFIED BY 1111
        DEFAULT TABLESPACE TS_SVA
        TEMPORARY TABLESPACE TS_SVA_TEMP
        PROFILE PF_SVACORE
        ACCOUNT UNLOCK
        PASSWORD EXPIRE
        
        
        DROP USER SVACORE;
        GRANT RL_SVACORE TO SVACORE;
        REVOKE RL_SVACORE TO SVACORE;
        
    --#9 (— –»Õ ¬ œ¿œ ≈ LAB2)
        ALTER USER SVACORE QUOTA unlimited  ON TS_SVA
        select * from dba_role_privs connect by prior granted_role = grantee start with grantee = '&SVACORE' order by 1,2,3;
        GRANT RESOURCE to SVACORE;
    --#10
        CREATE TABLE UNIVERSITY(
            UNIVERSITY_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            NAME VARCHAR2(20)
        )
        INSERT INTO UNIVERSITY VALUES(DEFAULT,'BSTU');
        INSERT INTO UNIVERSITY VALUES(DEFAULT,'BGUIR');
        INSERT INTO UNIVERSITY VALUES(DEFAULT,'BNTU');
        
        CREATE VIEW ALL_UNIVERSITY AS
            SELECT * FROM UNIVERSITY  
            
        SELECT * FROM ALL_UNIVERSITY
    --#11
        CREATE TABLESPACE SVA_QDATA
            DATAFILE 'SVA_QDATA.dbf'
            SIZE 10M
            AUTOEXTEND ON NEXT 5M
            MAXSIZE 20M
            EXTENT MANAGEMENT LOCAL
            OFFLINE
        
        ALTER TABLESPACE SVA_QDATA ONLINE
        ALTER USER SVACORE QUOTA 2M  ON SVA_QDATA
        
        select TABLESPACE_NAME from dba_tablespaces;
        CREATE TABLE TSSQ(
            VALUESX INT,
            SSS FLOAT
        )TABLESPACE SVA_QDATA
        
        INSERT INTO TSSQ VALUES(1,2.1);
        INSERT INTO TSSQ VALUES(2,5.3);
        INSERT INTO TSSQ VALUES(3,1.4);
        
        SELECT *FROM TSSQ     
        